### ISSUE TITLE
Is there any build instructions?

### ISSUE THREAD

**Issue by hustc12** [Alexander--/fdshare#1]
Thank you for providing this lib! However, neither can I find anywhere to download the built aar lib, nor find any build instructions which can lead me to build the lib by myself based on the source code. So, is there any one?
Thanks again!

**Comment by Alexander--** [comment]
You can find sort-of build instructions in https://github.com/chdir/fdshare/blob/master/.travis.yml (it describes rough sequences of actions to compile all code in [Travis-CI config format](https://docs.travis-ci.com/user/customizing-the-build/)). There is also an aar, as can be seen in the [sample project](https://github.com/chdir/fdshare/blob/master/example/build.gradle), but I would not recommend anyone to use it — you are much better off building your own version.

Note, that this project is in early experimental state, and you should not attempt use it on API < 15 (since doing so would reduce in file descriptor leaks).
